spring.application.name=AiAstrologer
gemini.api.key=AIzaSyDfqtLZpVIkBi5QMpGZrnL-sVuM8q3J52g
gemini.model=gemini-2.5-flash
FRONTEND_API=https://astroaiastro.netlify.app
#FRONTEND_API=http://localhost:5173
#server.port=8088
server.port=${PORT:8088}

